Remove pessimizing std::move
This fixes `--enable-paranoid-warnings --enable-werror` configurations'
`make check` on gcc 13.2 for me.  Previously we got e.g.:

error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]
  320 |     auto derivatives = std::move(nd_dns_##optype(a, b));

Which looks correct to me; copy elision is mandatory as of C++17 so the
std::move() is only an improvement on obsolete compilers.